# Generated by Django 4.0.1 on 2022-02-10 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='categoty',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
