# Generated by Django 4.0.1 on 2022-02-10 09:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_youtuber_categoty_youtuber_crew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('sony', 'sony'), ('fuji', 'fuji'), ('red', 'red'), ('penasonic', 'penasonic'), ('other', 'other')], max_length=225),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='categoty',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('gagets_review', 'gagets_review'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('film_making', 'film_making'), ('gaming', 'gaming'), ('cooking', 'cooking')], max_length=225),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
